### ISSUE TITLE
Autosaver is broken in current build

### ISSUE THREAD

**Issue by addstar** [AddstarMC/Pandora#6]
After enabling Autosaver, this is happening now on the latest paper builds. I thought it was working previously when I tested it so maybe it was a Paper change?
```
21:36:40 [WARN]: Plugin Pandora v1.0.7-SNAPSHOT-128 generated an exception while executing task 15075
java.lang.IllegalStateException: WorldSaveEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.2.jar:git-Paper-68]
        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758) ~[patched_1.14.2.jar:git-Paper-68]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.save(CraftWorld.java:1160) ~[patched_1.14.2.jar:git-Paper-68]
        at au.com.addstar.pandora.modules.autosave.RegionFileFlusher$SavingTask.run(RegionFileFlusher.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-68]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-68]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-68]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by Narimm** [comment]
Removed as no longer required
